# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  issue_comment:
    branches: [ master ]
    
jobs:
  my_first_job:
    name: My Job Name
    runs-on: ubuntu-latest
    steps:
      - uses: bbaldino/jitsi-ga-test@HEAD
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
            name: logs
            path: logs
